### PR TITLE
Remove legacy

### PR DESCRIPTION
**Pull request by bcvandendool**
Remove legacy app allowing migration of users.

## Description

As there is no plan for another wave of migrations we should remove this as its no longer necessary, and it reduces maintenance.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dasyad00 — COMMENTED** [review]
At the moment, there are no migrations specifically removing the legacy database. Will this be done manually?

**Comment by bcvandendool** [comment]
As it is a separate database that will have to be removed, it will have to be done manually.

**Review by dasyad00 — APPROVED** [review]

**Comment by dasyad00** [comment]
Just a thought, will the custom made django inside of requirements.txt be changed?

**Comment by bcvandendool** [comment]
Nah, django-cms will be removed soon enough anyhow.

**Pull request merged**
